workstations:
  - id: 11
  - id: 12
  - id: 13
  - id: 14

ssh:
  user: rbansal66
  base_ip: "130.207.121"
  ip_offset: 200

tunnel:
  node: "grom"
  port: 8999
  user: rbansal66
  server: "sky1.cc.gatech.edu"
